- name: launch one openstack instance
  connection: local
  hosts: local
  gather_facts: false  
  vars_files:
   - vars/metacloud_vars.yml

  tasks: 
 
  - name: Ensure New server is up. 
    nova_compute:
      state: present
      auth_url: "{{ lookup('env', 'OS_AUTH_URL') }}"
      login_username: "{{ lookup('env', 'OS_USERNAME') }}"
      login_password: "{{ lookup('env', 'OS_PASSWORD') }}"
      login_tenant_name: "{{ lookup('env', 'OS_TENANT_NAME') }}"
      name: gmorini-server
      # run nova image-list to get an image and put its id below. 
      image_id: "1ca2015e-71e0-45fe-9d9a-8427cd6c06da"
      # fill in your key name here
      key_name: "gmorini-pubkey"
      flavor_id: "44e0aeb8-95fd-4a18-bca0-be1eec8f42ac"
      security_groups: default
