---
- name: Ensure Lab is Up. 
  docker: 
    docker_api_version: 1.21
    image: "vallard/metaclient" 
    name: lab01 
    privileged: true
    ports: 
      - "2222:22"
      - "8001:8001"
      - "8002:8002"
      - "8003:8003"
      - "8004:8004"
      - "8005:8005"
      - "8006:8006"
      - "8007:8007"
      - "8008:8008"
      - "8009:8009"
      - "8010:8010"
