#cloud-config

write_files:
  - path: /etc/coreos-python.sh
    permissions: "0755"
    content: |
      #!/bin/bash

      ## Set up python
      PYPY_VERSION=2.4.0
      HOME=/home/core
      mkdir -p $HOME
      cd $HOME
      block-until-url https://bitbucket.org/pypy/pypy/downloads/pypy-$PYPY_VERSION-linux64.tar.bz2
      wget -O - https://bitbucket.org/pypy/pypy/downloads/pypy-$PYPY_VERSION-linux64.tar.bz2 |tar -xjf -
      mv -n pypy-$PYPY_VERSION-linux64 pypy
      ## library fixup
      mkdir -p pypy/lib
      ln -snf /lib64/libncurses.so.5.9 $HOME/pypy/lib/libtinfo.so.5

      mkdir -p $HOME/bin
      #
      cat > $HOME/bin/python <<EOF
      #!/bin/bash
      LD_LIBRARY_PATH=$HOME/pypy/lib:$LD_LIBRARY_PATH exec $HOME/pypy/bin/pypy "\$@"
      EOF
      #
      chmod +x $HOME/bin/python
      $HOME/bin/python --version
      wget http://benincosa.com/get-pip.py
      sudo $HOME/bin/python ~/get-pip.py


      echo '#!/bin/bash
      LD_LIBRARY_PATH=/home/core/pypy/lib:$LD_LIBRARY_PATH /home/core/pypy/bin/$(basename $0) $@'>$HOME/bin/pip

      chmod 755 $HOME/bin/pip

      # use 1.1.0 for the docker client to equal the same version of the server: 1.18 and not get bug. 
      sudo $HOME/bin/pip install -I docker-py==1.1.0
      
      # setup insecure registry
      mkdir -p /etc/systemd/system/
      cat > /etc/systemd/system/docker.service <<EOF
      [Unit]
      Description=Docker Application Container Engine
      Documentation=http://docs.docker.com
      After=docker.socket early-docker.target network.target
      Requires=docker.socket early-docker.target

      [Service]
      Environment=TMPDIR=/var/tmp
      EnvironmentFile=-/run/flannel_docker_opts.env
      MountFlags=slave
      LimitNOFILE=1048576
      LimitNPROC=1048576
      ExecStart=/usr/lib/coreos/dockerd daemon --host=fd:// --insecure-registry ci:5000 $DOCKER_OPTS $DOCKER_OPT_BIP $DOCKER_OPT_MTU $DOCKER_OPT_IPMASQ
      [Install]
      WantedBy=multi-user.target
      EOF

      systemctl daemon-reload
      systemctl restart docker


coreos:
  units:
    - name: "runcmd.service"
      command: "start"
      content: |
        [Unit]
        Description=Run a command
        [Service]
        TimeoutStartSec=0
        Type=oneshot
        KillMode=none
        ExecStart=/etc/coreos-python.sh
        RemainAfterExit=yes

ssh_authorized_keys:
  # include one or more SSH public keys
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3tlDaR7OUnYtSY0znXVKdkvubQWvHKHqavIhLK1wm9r1cm53lNRrEG4JALJ5gGfJqAwztY8NIOXi03gaIPkl/8GTsBxNEiJI+K6fG34RyIUmy36B9/O1ny2KkNpw+KQ2jX2zPwKBtNTTdiVxFCFTJa5AnaIDvMByKCbw2ULbcyLeXALYHYybf2caFreI0uhwXxj3BKuXfZD1eHufsln8+ZqSgUM14vebpZv86yi0xJq41hjj0hUklHk3jwbFgYtql7fQzFFJnGi8nRRl4dxrsQZarhGYijsNbTHjEK1KJtI1DPFqpzuhYE+iYfXn0xjCtMuiVWwRngR6Ug86ATTDb
  - ssh-dss AAAAB3NzaC1kc3MAAACBAMJubadTbAOOxe3eTuTKdaHArA59qYmWKPwoiVrIokytEqKaoBC8hhu+GMy5OuXrM+8A3k36I0YjMcN5tWQ0fHeH2QysQWonndztixzs8m71Dau7OTOILDZaF6FP+BN8CLje4pW4e4RHxF7Eko0GIF82hJI+7xnj5YQB2nrHWNQ/AAAAFQCVTRrwUUv9JdT4WtjM+sl/BwEz+QAAAIAYl/OHqw3NYfccH32kRpRlVSHKE48xf+UhYrrMzga7C0Ub6ZMUvaBkapr1Gv9YNLlazbRC2jgaakiXEBHiAQZMiGvpNAQW8zm7V+VRS8VZynA0vkM7//gDBCms56CYsPZI/V7Qxpyl0igRaJo6zq5KZHkKYNBWt84Sh9pFsWtngwAAAIALcj+nJziobZsSDQV5dqG5CjLpDZbufNeuFOoBsjoMWyFPkLJoNYfTjJfqU8a+dlBdi4V8lae5RsF+eHoVrGu/ehwty6LD+QKFUNAtTR0zqtuydqlosXodejarmTpLppnPnS4eAQ3oh8o2FZnLBX4eOlw4qPEPbDrFNbDQ6q7eUw==
