      # setup insecure registry
      mkdir -p /etc/systemd/system/
      cat > /etc/systemd/system/docker.service <<EOF
      [Unit]
      Description=Docker Application Container Engine
      Documentation=http://docs.docker.com
      After=docker.socket early-docker.target network.target
      Requires=docker.socket early-docker.target

      [Service]
      Environment=TMPDIR=/var/tmp
      EnvironmentFile=-/run/flannel_docker_opts.env
      MountFlags=slave
      LimitNOFILE=1048576
      LimitNPROC=1048576
      ExecStart=/usr/lib/coreos/dockerd --daemon --host=fd:// --insecure-registry ci:5000 $DOCKER_OPTS $DOCKER_OPT_BIP $DOCKER_OPT_MTU $DOCKER_OPT_IPMASQ
      [Install]
      WantedBy=multi-user.target
      EOF

      systemctl daemon-reload
      systemctl restart docker

